### ISSUE TITLE
卸载

### ISSUE THREAD

**Issue by cloud-mood** [miaoermua/openwrt-leigodacc-manager#3]
怎么卸载，找不到软件包

**Comment by miaoermua** [comment]
> 怎么卸载，找不到软件包

请使用管理器中的“卸载”功能，管理器就是干这个事的，雷神官方并没有提供卸载功能，并且不是通过软件源进行安装的。卸载功能兼容官方版本和 lean 版，lean 版是我和 lean 提供的可编译集成版本。

如果你需要体验完整功能建议使用 CatWrt.v24.9 或 QWRT & LEDE

**Comment by cloud-mood** [comment]
不好意思，你说的这个管理器是什么。我在openwrt中找不到

**Comment by miaoermua** [comment]
> 不好意思，你说的这个管理器是什么。我在openwrt中找不到

管理器就是一个 sh 脚本，是放在 ssh 终端上运行的。

相关博客：

https://www.miaoer.net/posts/blog/openwrt-leigodacc-manager

https://www.miaoer.net/posts/blog/ssh-connection-to-openwrt

**Comment by cloud-mood** [comment]
谢谢.已经卸载了
